on:
  push:
    paths:
      - vignettes/performance.Rmd.og

name: Render performance .Rmd vignette

jobs:
  render:
    name:  Render performance .Rmd vignette
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install package and dependencies
        run: |
          remotes::install_local(dependencies = TRUE)
          remotes::install_cran(c("microbenchmark", "ggplot2", "FD", "adiv",
                                  "hillR", "SYNCSA"))
        shell: Rscript {0}

      - name: Render vignette
        run: |
          knitr::knit('vignettes/performance.Rmd.og',
                      output = 'vignettes/performance.Rmd')
        shell: Rscript {0}
